<a href="https://colab.research.google.com/github/KuruvaPoojitha11/Deep-Learning-lab-program/blob/main/Deep_Learning_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


Lab 1

In [2]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


Program to predict sum of two numbers

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.3)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/5
88/88 [==============================] - 2s 5ms/step - loss: 15556.7070 - val_loss: 10771.4014
Epoch 2/5
88/88 [==============================] - 0s 3ms/step - loss: 7105.7666 - val_loss: 3354.0293
Epoch 3/5
88/88 [==============================] - 0s 3ms/step - loss: 1677.1837 - val_loss: 704.3970
Epoch 4/5
88/88 [==============================] - 0s 3ms/step - loss: 405.0650 - val_loss: 177.7759
Epoch 5/5
63/63 [==============================] - 0s 1ms/step - loss: 29.6243
Test Loss: 29.624338150024414
1/1 [==============================] - 0s 91ms/step
Predicted Sum: 68.72559356689453


In [4]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=8, batch_size=75, validation_split=0.5)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/8
54/54 [==============================] - 1s 8ms/step - loss: 11940.2754 - val_loss: 10351.5557
Epoch 2/8
54/54 [==============================] - 0s 5ms/step - loss: 8080.1074 - val_loss: 5303.1538
Epoch 3/8
54/54 [==============================] - 0s 3ms/step - loss: 3281.5476 - val_loss: 1471.4875
Epoch 4/8
54/54 [==============================] - 0s 5ms/step - loss: 661.8792 - val_loss: 149.9869
Epoch 5/8
54/54 [==============================] - 0s 4ms/step - loss: 52.0466 - val_loss: 13.7040
Epoch 6/8
54/54 [==============================] - 0s 3ms/step - loss: 10.2626 - val_loss: 8.4231
Epoch 7/8
54/54 [==============================] - 0s 4ms/step - loss: 7.0325 - val_loss: 5.9346
Epoch 8/8
63/63 [==============================] - 0s 2ms/step - loss: 4.1963
Test Loss: 4.1962504386901855
1/1 [==============================] - 0s 89ms/step
Predicted Sum: 69.50979614257812
